# Site settings
title: CoCalc Tutorial
motto: A tutorial for anyone wanting to use CoCalc, especially for teaching
description: A tutorial for anyone wanting to use CoCalc, especially for teaching
baseurl: ""
url: "https://tutorial.cocalc.com" # the base hostname & protocol for your site

footer-links:
  github: sagemathinc/cocalc
  twitter: cocalc_com
  email: info+tutorial@sagemath.com

# Build settings
markdown: kramdown

# Additional gems
gems:
  - jekyll-titles-from-headings
